config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users', to: 'users/sessions#index'
    get '/users/:id', to: 'users/sessions#show'
    patch '/users/:id', to: 'users/registrations#verify'
    put '/users/:id', to: 'users/registrations#reject'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [ :show ] do
    resources :favors, only: [ :new, :create ]
    resources :referrals, only: [ :new, :create, :show ]
  end
  resources :referrals, only: [ :index, :show ]
  resources :favors, only: [ :index, :show ]
  resources :inquiries, only: [ :create, :index, :update ]
  get '/about', to: 'pages#about'
  get '/join', to: 'pages#join'
  get '/contact', to: 'pages#contact'
end

app/views/shared/_banner.html.erb
<div class="banner">
  <h5 class="text-center mb-0">Welcome to the</h5>
  <h1 class="text-center mb-4"><strong>Quick Favor Club</strong></h1>


  <h5 class="my-1 text-center">We’re a close community of passionate do’ers looking to help each other out with quick favors!</h5>


  <div class="center my-5">
    <div>
     <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
     <%= link_to "Join Us", join_path, class: "btn btn-primary ml-1"  %>
    </div>
  </div>

  <p class="mt-4 mb-1 text-center quote-tag"><i>“If we create networks with the sole intention of getting something, we won’t succeed. We can’t pursue the benefits of networks; the benefits ensue from investments in meaningful activities and relationships.”</i><br><br>Adam Grant, Give and Take</p>
</div>

app/views/shared/_bottomnavbar.html.erb
<% if @unhide_favornavbar == true %>
  <div class="bottom-navbar">
    <div class="center my-3">
      <%= link_to "Request a Favor", new_user_favor_path(current_user), class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>


<% if @unhide_referralnavbar == true %>
  <div class="bottom-navbar">
    <div class="center my-3">
      <%= link_to "Invite a Friend", new_user_referral_path(current_user), class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

<% if @unhide_joinnavbar == true %>
  <div class="bottom-navbar">
    <div class="center my-3">
      <%= link_to "Interested to Join?", join_path, class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in? %>
    <%= link_to "Quick Favor Club", about_path %>
  <% else %>
    <%= link_to "Quick Favor Club", root_path %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.status == "verified" %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Favors", favors_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Community", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <% if current_user.admin == false %>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Inquiries", inquiries_path, class: "nav-link" %>
            </li>
          <% end %>

          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "About", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>