config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users', to: 'users/sessions#index'
    get '/users/:id', to: 'users/sessions#show'
    patch '/users/:id', to: 'users/registrations#verify'
    put '/users/:id', to: 'users/registrations#reject'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [ :show ] do
    resources :favors, only: [ :new, :create ]
    resources :referrals, only: [ :new, :create, :show ]
  end
  resources :referrals, only: [ :index, :show ]
  resources :favors, only: [ :index, :show ]
  resources :inquiries, only: [ :create, :index, :update ]
  get '/about', to: 'pages#about'
  get '/join', to: 'pages#join'
  get '/contact', to: 'pages#contact'
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user, optional: true

  validates :subject, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  skip_before_action :authenticate_user!

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if user_signed_in?
      @inquiry.user = current_user
    end

    if @inquiry.save
      InquiryMailer.with(inquiry: @inquiry).new_inquiry.deliver_now
      if user_signed_in
        redirect_to favors_path
      else
        redirect_to root_path
      end
    else
      redirect_to contact_path, notice: "Oops, think you missed a question!"
    end
  end

  def index
    @inquiries = Inquiry.all.sort_by(&:created_at).reverse
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    @inquiry.responded = true

    if @inquiry.save
      redirect_to inquiries_path, notice: "Done!"
    else
      redirect_to inquiries_path, notice: "Oops, something went wrong."
    end
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:subject, :message, :first_name, :last_name, :email)
  end
end

app/views/inquiries/index.html.erb
<% if current_user.nil? || current_user.admin == false %>
  <p class="text-center">Oops! You're not allowed here. &#128584;</p>

  <%= link_to "< back", :back %>
<% else %>
  <h2 class="text-center mb-4">&#128588; Inquiries &#128588;</h2>

  <h6 class="text-center mt-4 mb-3"><strong>New Inquiries</strong></h6>

  <% @inquiries.each do |inquiry| %>
    <% if inquiry.responded == false %>
      <div class="profile-container">
        <div class="d-flex">
          <p class="flex-grow-1"><strong>Subject</strong>: <%= inquiry.subject %></p>
          <% if (inquiry.created_at.to_date) > (Date.today - 7) %>
            <p class="new-tag my-0 ml-2">NEW</p>
          <% end %>
        </div>
        <% if inquiry.message.present? %>
          <p><strong>Message</strong>: <%= inquiry.message %></p>
        <% end %>
        <% if inquiry.user.present? %>
          <p class="mb-0"><strong>Posted by</strong>: <%= inquiry.user.full_name %></p>
          <p><strong>Contact</strong>: <%= inquiry.user.email %></p>
        <% end %>
        <% if inquiry.first_name.present? %>
          <p class="mb-0"><strong>Posted by</strong>: <%= inquiry.first_name %> <%= inquiry.last_name %></p>
          <p><strong>Contact</strong>: <%= inquiry.email %></p>
        <% end %>
        <p><strong>Date received</strong>: <%= inquiry.created_at.to_date %></p>
        <%= link_to "Mark responded", inquiry_path(inquiry), :method => :patch, data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  <% end %>

  <h6 class="text-center mt-4 mb-3"><strong>Past Inquiries</strong></h6>

  <% @inquiries.each do |inquiry| %>
    <% if inquiry.responded == true %>
      <div class="profile-container">
        <p><strong>Subject</strong>: <%= inquiry.subject %></p>
        <% if inquiry.message.present? %>
          <p><strong>Message</strong>: <%= inquiry.message %></p>
        <% end %>
        <% if inquiry.user.present? %>
          <p class="mb-0"><strong>Posted by</strong>: <%= inquiry.user.full_name %></p>
          <p><strong>Contact</strong>: <%= inquiry.user.email %></p>
        <% end %>
        <% if inquiry.first_name.present? %>
          <p class="mb-0"><strong>Posted by</strong>: <%= inquiry.first_name %> <%= inquiry.last_name %></p>
          <p><strong>Contact</strong>: <%= inquiry.email %></p>
        <% end %>
        <p><strong>Date received</strong>: <%= inquiry.created_at.to_date %></p>
      </div>
    <% end %>
  <% end %>
<% end %>